spring:
  datasource:
    url: jdbc:mysql://localhost:3306/furniture_shop
    username: root
    password: A123456Qw1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: false
        jdbc:
          time_zone: Europe/Moscow
        #search:
        #  backend:
        #    directory:
        #      type: local-filesystem
        #      root: src/main/resources/indexes
  jwt:
    secret:
      access: ${JWT_ACCESS_SECRET_KEY}
      refresh: ${JWT_REFRESH_SECRET_KEY}
    life-time:
      # Срок жизни = 1 день в миллисекундах
      access: 86400000
      # Срок жизни = 60 дней в миллисекундах
      refresh: 5184000000
  mail:
    mail_from: redaschyup@yandex.ru
    host: smtp.yandex.ru
    port: 587
    username: redaschyup
    # Это сгенерированный пароль приложения, а не от яндекс-аккаунта
    password: ${MAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.yandex.ru
          timeout: 20000
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB