spring:
  datasource:
    url: jdbc:mysql://localhost:3306/furniture_shop
    username: root
    password: A123456Qw1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: false
        #search:
        #  backend:
        #    directory:
        #      type: local-filesystem
        #      root: src/main/resources/indexes
  security:
    user:
      name: name
      password: password
  mail:
    mail_from: redaschyup@yandex.ru
    host: smtp.yandex.ru
    port: 587
    username: redaschyup
    # Это сгенерированный пароль приложения, а не от яндекс-аккаунта
    password: jduyjgcjwxptrerz
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.yandex.ru
          timeout: 20000
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB